FROM openjdk:21
LABEL maintainer="itsupport@gmail.com"
ADD target/demo_sb_calculator-0.0.1-SNAPSHOT.jar demo_sb_calculator-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar","demo_sb_calculator-0.0.1-SNAPSHOT.jar"]
EXPOSE 8092
